apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
        - name: app
          image: spotik/history:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/configs
              readOnly: true
          env:
            - name: APP_HISTORY_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: history-dsn
      volumes:
        - name: config-volume
          configMap:
            name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: history
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: history