apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spotik-gateway
  annotations:
    # Эта аннотация берет 2-ю группу захвата (.*) и использует её как путь для бэкенда
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # Явно разрешаем использование регулярных выражений
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          # Catalog
          - path: /catalog(/|$)(.*)
            pathType: ImplementationSpecific # ВАЖНО: Изменено с Prefix
            backend:
              service:
                name: catalog
                port:
                  number: 80

          # Library
          - path: /library(/|$)(.*)
            pathType: ImplementationSpecific # ВАЖНО: Изменено с Prefix
            backend:
              service:
                name: library
                port:
                  number: 80

          # Media
          - path: /media(/|$)(.*)
            pathType: ImplementationSpecific # ВАЖНО: Изменено с Prefix
            backend:
              service:
                name: media
                port:
                  number: 80

          # History
          - path: /history(/|$)(.*)
            pathType: ImplementationSpecific # ВАЖНО: Изменено с Prefix
            backend:
              service:
                name: history
                port:
                  number: 80