kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # --- Ingress Ports ---
      - containerPort: 80       # Порт внутри Kind (Nginx)
        hostPort: 9999          # <--- ТВОЙ НОВЫЙ ПОРТ НА ХОСТЕ
        protocol: TCP
        listenAddress: "127.0.0.1"
      - containerPort: 443
        hostPort: 443           # HTTPS оставляем или можно убрать, если не нужен
        protocol: TCP
        listenAddress: "127.0.0.1"

      # --- Databases ---
      - containerPort: 30001
        hostPort: 55432 # Catalog DB
        listenAddress: "127.0.0.1"
      - containerPort: 30002
        hostPort: 55433 # Library DB
        listenAddress: "127.0.0.1"
      - containerPort: 30003
        hostPort: 55434 # Media DB
        listenAddress: "127.0.0.1"
      - containerPort: 30004
        hostPort: 55435 # History DB
        listenAddress: "127.0.0.1"

      # --- MinIO ---
      - containerPort: 30090
        hostPort: 9000
        listenAddress: "127.0.0.1"
      - containerPort: 30091
        hostPort: 9001
        listenAddress: "127.0.0.1"